// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Placar
{
        public const string achievement_you_made_5000_points = "CgkIr9nfgtUJEAIQAg"; // <GPGSID>
        public const string achievement_you_made_1000_points = "CgkIr9nfgtUJEAIQAQ"; // <GPGSID>
        public const string achievement_you_made_2000000_points = "CgkIr9nfgtUJEAIQCg"; // <GPGSID>
        public const string achievement_you_made_20000_points = "CgkIr9nfgtUJEAIQBA"; // <GPGSID>
        public const string achievement_you_made_10000_points = "CgkIr9nfgtUJEAIQAw"; // <GPGSID>
        public const string leaderboard_challenges_basketball_ranking = "CgkIr9nfgtUJEAIQAA"; // <GPGSID>
        public const string achievement_you_made_500000_points = "CgkIr9nfgtUJEAIQCA"; // <GPGSID>
        public const string achievement_you_made_100000_points = "CgkIr9nfgtUJEAIQBg"; // <GPGSID>
        public const string achievement_you_made_200000_points = "CgkIr9nfgtUJEAIQBw"; // <GPGSID>
        public const string achievement_you_made_50000_points = "CgkIr9nfgtUJEAIQBQ"; // <GPGSID>
        public const string achievement_you_made_1000000_points = "CgkIr9nfgtUJEAIQCQ"; // <GPGSID>

}

